{% set name = "path.py" %}
{% set version = "11.0.1" %}
{% set checksum = "e7eb9d0ca4110d9b4d7c9baa0696d8c94f837d622409cefc5ec9e7c3d02ea11f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python
    - importlib

test:
  imports:
    - path

about:
  home: https://github.com/jaraco/path.py
  license: MIT
  summary: A module wrapper for os.path
  description: |
    path.py implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://pathpy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path.py

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
