travis:
  secure:
    BINSTAR_TOKEN: ZPJtzNzvugeCfyou9vC7mjoKsttD0BXU4h4jzkwQmtLFA+CZREOpBja0cFnR+oa7XuNXzmGELHnHhB2EyU1KTW+qBwE0dkEwQuFuVTuN5IkxG3aYkNC1tX1yRT0Nn9Ex3NzKKU7+yUnAgfQnXKZ/TQQBmFQe8Nmw9urR0v+vQSCkyx/firPhxEx0ZVTtri6DO6l8q7+cV4cotqX2vRSXPS+PJANTp256qru4/gFvn6Azu5l3j0aMfoHcU2RBN92azcHOEUx0nrj2GtYknp6MCA7lcs8Rqhn+K8dGo9oY3PF3ztfmhkvvukgCaCBivI8pR+Ce5ScWRbjWGKEcniS0JEwfekSO7DfU0BNBiQU+EL4g5SSq76gaR6RYt2mpcFzAAJA3ydedcuSgmYvZB9TMX3nSXtqzg16gmJzf/hMBGVyrCiMWKksV8dZHd1Zkoa9c69AuzeSboH5Mvl7l6OuOPhqG24x76YjkGkWalBtao/AdqHXUODFQq2xF9ufG4k3qpHQr+DZiMNbSTKN4xsknjuA10KxV06D5tKipXJ7gRGxLS/CHQt5CClAIxdEBFT27tXEN7nJT/TvvMz+DuGXecIW5dMoxiLkRS27A+8sIdDfWdkR+pWys+rYOVlzBwaR6FljNElL3vcmB0gjxgNXtJDPedTwwwUNjxYWuPrLb2DI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
