travis:
  secure:
    BINSTAR_TOKEN: M72rcNVk5sH5zJYSquDmMDWnqT3zwksK27e9p5sVhHvCnBXO8Rlw2o+XKJhUiov1wu06MfTpaZJZYZHOMzU57ii+AvZ73brIWGrvHMCO8KX9roBsPhIsyby2mP/mZSGOUhQ0pPNpDJXwH4mtjPtBpY5kg+Qj5qMpo0uXYkZQxdtBzITQlaEvBq8dQ2DRtKri24n534THY4wWgzz5igqy1fAQzyNpv59kI7bz+q1G6vwLl38WG2sVJsL9g3VXVse8Twm3E4CBs8jYjwnmUJevkudFji+DA2NPXj40oSUEmgsMbfVXXJqFboGOSd9VuVLfHlku+jJKPM+6B/kAUTEA4mZjNHxb7/iSVPAoOiQzRSdZ85HnLMB58+KqTwhITC4cjxeeL4ZHeZ78plv1+Pjfq3QF4/JQiHYGcYnfDb59gyrvbDaRcXG75vspRpIs/xPNF2+xkE9yJUVRyYSGqH0Ykcv5X2lxxUbcgllWBEOjXZMSduhfdKb8z5D3Zg1JN/OrUbilm03ScsmjXKttezeROe/sDF5GcfZehDJK1WOhaXnoRZ9Eqdo5M/XPe8KEtr4ODd6Mvbi+xDtFhgGivR4ErUxED9ILy8+JIJDVEvxluAyLLutK6zhb+OIbSCOiEbZSb23G0Czs3TDid+3nxlM0H3r6ApWeqhLXgTVuKUpl7ck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
